//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingData
    {
        public int id { get; set; }
        public string appname { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> bill_from { get; set; }
        public Nullable<System.DateTime> bill_to { get; set; }
        public Nullable<System.DateTime> bill_paid_date { get; set; }
        public Nullable<int> bill_seconds { get; set; }
        public Nullable<int> bill_calls { get; set; }
        public string Invoice { get; set; }
    }
}
