//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int id { get; set; }
        public string category1 { get; set; }
        public Nullable<int> category_order { get; set; }
        public Nullable<bool> inverted { get; set; }
        public Nullable<bool> autofail { get; set; }
    }
}
