//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainMessage
    {
        public int id { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public string who_added { get; set; }
        public string appname { get; set; }
        public Nullable<System.DateTime> archived { get; set; }
    }
}
