//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class exportQueue
    {
        public int id { get; set; }
        public Nullable<int> fileOwner { get; set; }
        public string fileName { get; set; }
        public string fileUrl { get; set; }
        public Nullable<System.DateTime> exportDate { get; set; }
        public Nullable<bool> status { get; set; }
        public string exportType { get; set; }
    }
}
