//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_notifications
    {
        public int id { get; set; }
        public string role { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_closed { get; set; }
        public string closed_by { get; set; }
        public string close_reason { get; set; }
        public Nullable<int> form_id { get; set; }
        public Nullable<double> form_position { get; set; }
        public string opened_by { get; set; }
        public Nullable<int> sup_override { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<System.DateTime> escalated { get; set; }
        public string escalated_by { get; set; }
        public Nullable<System.DateTime> escalated_closed { get; set; }
    }
}
