//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class moduleList
    {
        public int id { get; set; }
        public string moduleName { get; set; }
        public string moduleFunction { get; set; }
        public string moduleWidth { get; set; }
        public string moduleControlName { get; set; }
        public Nullable<int> admin { get; set; }
        public Nullable<int> qa { get; set; }
        public Nullable<int> agent { get; set; }
        public Nullable<int> supervisor { get; set; }
        public Nullable<int> client { get; set; }
        public Nullable<int> qa_lead { get; set; }
        public Nullable<int> Trainee { get; set; }
        public Nullable<int> Manager { get; set; }
        public Nullable<int> default_order { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> Center_manager { get; set; }
        public Nullable<int> calibrator { get; set; }
        public Nullable<bool> call_center { get; set; }
        public Nullable<int> partner { get; set; }
        public Nullable<int> recalibrator { get; set; }
        public Nullable<int> client_calibrator { get; set; }
        public Nullable<int> tango_tl { get; set; }
    }
}
