//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class molly_phone_data
    {
        public int id { get; set; }
        public string CalledNumber { get; set; }
        public string FranchiseLocation { get; set; }
        public string agentgroup { get; set; }
    }
}
