//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pay2sc_dev
    {
        public string startdate { get; set; }
        public Nullable<decimal> @base { get; set; }
        public string calltime { get; set; }
        public string reviewtime { get; set; }
        public string swing_reviewtime { get; set; }
        public Nullable<decimal> efficiency { get; set; }
        public decimal calibration_score { get; set; }
        public int num_calibrations { get; set; }
        public Nullable<double> cal_percent { get; set; }
        public Nullable<decimal> eff_percent { get; set; }
        public Nullable<int> num_disputes { get; set; }
        public Nullable<double> scorecard_hours { get; set; }
        public Nullable<double> dispute_cost { get; set; }
        public string appname { get; set; }
        public string websitetime { get; set; }
        public string short_name { get; set; }
        public Nullable<int> scorecard { get; set; }
        public Nullable<int> websites { get; set; }
        public Nullable<double> avg_website { get; set; }
        public string user_type { get; set; }
    }
}
