//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportField
    {
        public int id { get; set; }
        public string field_name { get; set; }
        public string field_sql { get; set; }
        public string field_table { get; set; }
        public string field_type { get; set; }
    }
}
