//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class spotcheck
    {
        public int id { get; set; }
        public Nullable<int> f_id { get; set; }
        public Nullable<int> x_id { get; set; }
        public string checked_by { get; set; }
        public Nullable<System.DateTime> checked_date { get; set; }
        public string disposition { get; set; }
        public string notes { get; set; }
        public string notes1 { get; set; }
        public string check_reason { get; set; }
        public string assigned_to { get; set; }
        public string who_added { get; set; }
        public Nullable<System.DateTime> when_added { get; set; }
        public string close_reason { get; set; }
        public Nullable<System.DateTime> review_start { get; set; }
        public string reviewer_name { get; set; }
        public Nullable<System.DateTime> reviewer_start { get; set; }
        public string qa_qa_name { get; set; }
        public Nullable<int> qa_qa_f_id { get; set; }
    }
}
