//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timezone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Timezone()
        {
            this.TimezoneAdjustmentRules = new HashSet<TimezoneAdjustmentRule>();
        }
    
        public int Id { get; set; }
        public string Identifier { get; set; }
        public string StandardName { get; set; }
        public string DisplayName { get; set; }
        public string DaylightName { get; set; }
        public Nullable<bool> SupportsDaylightSavingTime { get; set; }
        public Nullable<int> BaseUtcOffsetSec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimezoneAdjustmentRule> TimezoneAdjustmentRules { get; set; }
    }
}
