//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_reports
    {
        public int id { get; set; }
        public string username { get; set; }
        public string report_query { get; set; }
        public Nullable<System.DateTime> report_added { get; set; }
        public string emails { get; set; }
        public string report_schedule { get; set; }
        public string report_name { get; set; }
        public Nullable<System.DateTime> last_posted { get; set; }
        public Nullable<bool> active { get; set; }
        public string report_appname { get; set; }
        public Nullable<bool> run_test { get; set; }
        public string run_query { get; set; }
        public string report_repeat { get; set; }
    }
}
