//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDash
    {
        public string username { get; set; }
        public string appname { get; set; }
        public string controlname { get; set; }
        public Nullable<int> controlorder { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public int id { get; set; }
    }
}
