//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vb_ss_data2
    {
        public int id { get; set; }
        public Nullable<int> xcc_id { get; set; }
        public Nullable<int> num_pressed { get; set; }
        public string timestamp { get; set; }
        public string orig_number { get; set; }
        public string confidence { get; set; }
        public string orig_time { get; set; }
    }
}
