//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFormSimple
    {
        public int F_ID { get; set; }
        public Nullable<int> review_ID { get; set; }
        public string reviewer { get; set; }
        public string appname { get; set; }
        public Nullable<decimal> total_score { get; set; }
        public Nullable<double> call_length { get; set; }
        public Nullable<System.DateTime> week_ending_date { get; set; }
        public Nullable<int> num_missed { get; set; }
        public string AGENT { get; set; }
        public string TIMESTAMP { get; set; }
        public string CALL_TYPE { get; set; }
        public string leadid { get; set; }
        public string AGENT_GROUP { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public int X_ID { get; set; }
        public Nullable<int> MAX_REVIEWS { get; set; }
        public Nullable<System.DateTime> review_started { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> call_date { get; set; }
        public string audio_link { get; set; }
        public string audio_user { get; set; }
        public string audio_password { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public string CAMPAIGN { get; set; }
        public Nullable<int> bad_call { get; set; }
        public string SESSION_ID { get; set; }
        public string pass_fail { get; set; }
        public Nullable<int> scorecard { get; set; }
        public Nullable<int> review_time { get; set; }
        public Nullable<bool> wasEdited { get; set; }
        public string website { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<decimal> calib_score { get; set; }
        public Nullable<decimal> edited_score { get; set; }
        public Nullable<bool> onAWS { get; set; }
        public Nullable<int> call_duration { get; set; }
        public string Scorecard_name { get; set; }
        public string team_lead { get; set; }
        public Nullable<double> display_score { get; set; }
        public string sc_review_type { get; set; }
        public string notification_status { get; set; }
        public Nullable<bool> manager_sees_supervisor { get; set; }
        public Nullable<bool> client_visible { get; set; }
        public Nullable<System.DateTime> xcc_review_date { get; set; }
    }
}
