//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAV_DATA
    {
        public int ID { get; set; }
        public string filename { get; set; }
        public Nullable<System.DateTime> file_date { get; set; }
        public string file_directory { get; set; }
        public string appname { get; set; }
        public string session_id { get; set; }
        public string audio_user { get; set; }
        public string audio_password { get; set; }
        public string phone_num { get; set; }
        public Nullable<int> sc_id { get; set; }
        public Nullable<System.DateTime> wav_added { get; set; }
    }
}
