//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPlan
    {
        public int ID { get; set; }
        public Nullable<int> CoachingLogID { get; set; }
        public string Owner { get; set; }
        public string Action { get; set; }
        public System.DateTime Timeline { get; set; }
    
        public virtual CoachingLog CoachingLog { get; set; }
    }
}
