//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class agenda_topics
    {
        public int id { get; set; }
        public string who_created { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<int> agenda_id { get; set; }
        public string section { get; set; }
        public string header { get; set; }
        public string point { get; set; }
        public string question { get; set; }
        public string page_link { get; set; }
        public Nullable<System.DateTime> date_completed { get; set; }
        public string who_completed { get; set; }
    }
}
