//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachingLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoachingLog()
        {
            this.ActionPlans = new HashSet<ActionPlan>();
        }
    
        public int ID { get; set; }
        public string QA { get; set; }
        public string TL { get; set; }
        public System.DateTime CoachingDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Reason { get; set; }
        public Nullable<int> ActionID { get; set; }
        public string DiscussionPoints { get; set; }
        public string QAResponse { get; set; }
        public Nullable<System.DateTime> QASigned { get; set; }
        public Nullable<System.DateTime> TLSigned { get; set; }
        public Nullable<System.DateTime> ManagerSigned { get; set; }
        public Nullable<int> Scorecard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionPlan> ActionPlans { get; set; }
        public virtual CorrectiveAction CorrectiveAction { get; set; }
    }
}
