//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dba_indexDefragStatus
    {
        public int databaseID { get; set; }
        public string databaseName { get; set; }
        public int objectID { get; set; }
        public int indexID { get; set; }
        public short partitionNumber { get; set; }
        public double fragmentation { get; set; }
        public int page_count { get; set; }
        public long range_scan_count { get; set; }
        public string schemaName { get; set; }
        public string objectName { get; set; }
        public string indexName { get; set; }
        public System.DateTime scanDate { get; set; }
        public Nullable<System.DateTime> defragDate { get; set; }
        public bool printStatus { get; set; }
        public int exclusionMask { get; set; }
    }
}
