//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class esto_agents
    {
        public string AGENT { get; set; }
        public string AGENT_GROUP { get; set; }
        public int id { get; set; }
        public string supervisor { get; set; }
    }
}
