//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPI_notes
    {
        public int id { get; set; }
        public string note { get; set; }
        public Nullable<int> fpi_id { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
    }
}
