//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class keyword_tracking
    {
        public int id { get; set; }
        public Nullable<int> kw_id { get; set; }
        public Nullable<System.DateTime> kw_changed { get; set; }
        public string kw_changed_by { get; set; }
        public string kw_update_type { get; set; }
        public string kw_utterance { get; set; }
    }
}
