//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class next_item
    {
        public int id { get; set; }
        public string username { get; set; }
        public string call_type { get; set; }
        public Nullable<int> allow_others { get; set; }
        public string user_role { get; set; }
        public Nullable<int> next_id { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
