//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int id { get; set; }
        public string session_id { get; set; }
        public string assigned_to { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public Nullable<bool> acknowledged { get; set; }
        public Nullable<int> form_id { get; set; }
        public Nullable<System.DateTime> ack_date { get; set; }
        public string ack_by { get; set; }
        public string opened_by { get; set; }
        public Nullable<System.DateTime> qa_view { get; set; }
        public string qa_who { get; set; }
        public string qa_decision { get; set; }
        public string supe_answer_dispute { get; set; }
        public Nullable<System.DateTime> supe_date { get; set; }
        public string supe_decision { get; set; }
        public Nullable<int> sup_override { get; set; }
    }
}
