//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class review_documents
    {
        public int id { get; set; }
        public string filename { get; set; }
        public string s3key { get; set; }
        public int f_id { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
        public string Description { get; set; }
        public string username { get; set; }
    }
}
