//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulingRequieredQA
    {
        public int Id { get; set; }
        public string appname { get; set; }
        public Nullable<int> scorecardId { get; set; }
        public System.DateTime selectedDate { get; set; }
        public int hourId { get; set; }
        public Nullable<int> requiredQAs { get; set; }
    }
}
