//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class scoring_history
    {
        public int id { get; set; }
        public Nullable<int> f_id { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
        public string who_changed { get; set; }
        public string score_type { get; set; }
    }
}
