//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class submit_listen
    {
        public int id { get; set; }
        public Nullable<int> x_id { get; set; }
        public string reviewer { get; set; }
        public Nullable<System.DateTime> save_time { get; set; }
        public Nullable<int> f_id { get; set; }
        public Nullable<System.DateTime> last_seen { get; set; }
        public Nullable<int> call_length { get; set; }
        public Nullable<double> review_time { get; set; }
        public Nullable<int> scorecard { get; set; }
        public string scorecard_name { get; set; }
    }
}
