//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class synopsisFix
    {
        public int id { get; set; }
        public Nullable<int> fix_order { get; set; }
        public string source_text { get; set; }
        public string replace_text { get; set; }
        public Nullable<int> scorecard { get; set; }
    }
}
