//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_columns_backup
    {
        public int object_id { get; set; }
        public int index_id { get; set; }
        public int index_column_id { get; set; }
        public int column_id { get; set; }
        public byte key_ordinal { get; set; }
        public byte partition_ordinal { get; set; }
        public Nullable<bool> is_descending_key { get; set; }
        public Nullable<bool> is_included_column { get; set; }
    }
}
