//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimezoneAdjustmentRule
    {
        public int Id { get; set; }
        public Nullable<int> TimezoneId { get; set; }
        public Nullable<int> RuleNo { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<bool> DaylightTransitionStartIsFixedDateRule { get; set; }
        public Nullable<int> DaylightTransitionStartMonth { get; set; }
        public Nullable<int> DaylightTransitionStartDay { get; set; }
        public Nullable<int> DaylightTransitionStartWeek { get; set; }
        public Nullable<int> DaylightTransitionStartDayOfWeek { get; set; }
        public Nullable<System.TimeSpan> DaylightTransitionStartTimeOfDay { get; set; }
        public Nullable<bool> DaylightTransitionEndIsFixedDateRule { get; set; }
        public Nullable<int> DaylightTransitionEndMonth { get; set; }
        public Nullable<int> DaylightTransitionEndDay { get; set; }
        public Nullable<int> DaylightTransitionEndWeek { get; set; }
        public Nullable<int> DaylightTransitionEndDayOfWeek { get; set; }
        public Nullable<System.TimeSpan> DaylightTransitionEndTimeOfDay { get; set; }
        public Nullable<int> DaylightDeltaSec { get; set; }
    
        public virtual Timezone Timezone { get; set; }
    }
}
