//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class XCC_REPORT_OLD
    {
        public string SESSION_ID { get; set; }
        public string AGENT { get; set; }
        public string DISPOSITION { get; set; }
        public string CAMPAIGN { get; set; }
        public string ANI { get; set; }
        public string DNIS { get; set; }
        public string TIMESTAMP { get; set; }
        public Nullable<System.DateTime> TALK_TIME { get; set; }
        public Nullable<System.DateTime> CALL_TIME { get; set; }
        public Nullable<System.DateTime> HANDLE_TIME { get; set; }
        public string CALL_TYPE { get; set; }
        public string LIST_NAME { get; set; }
        public Nullable<double> leadid { get; set; }
        public string AGENT_GROUP { get; set; }
        public Nullable<System.DateTime> HOLD_TIME { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<double> Datacapturekey { get; set; }
        public Nullable<double> Datacapture { get; set; }
        public string Status { get; set; }
        public string Program { get; set; }
        public int ID { get; set; }
        public string Datacapture_Status { get; set; }
        public string num_of_schools { get; set; }
        public Nullable<int> MAX_REVIEWS { get; set; }
        public Nullable<System.DateTime> review_started { get; set; }
        public string Number_of_Schools { get; set; }
        public string EducationLevel { get; set; }
        public string HighSchoolGradYear { get; set; }
        public string DegreeStartTimeframe { get; set; }
        public string College_1 { get; set; }
        public string DegreeOfInterest_1 { get; set; }
        public string School_1 { get; set; }
        public string AOI1_1 { get; set; }
        public string AOI2_1 { get; set; }
        public string L1_SubjectName_1 { get; set; }
        public string L2_SubjectName_1 { get; set; }
        public string College_2 { get; set; }
        public string DegreeOfInterest_2 { get; set; }
        public string School_2 { get; set; }
        public string AOI1_2 { get; set; }
        public string AOI2_2 { get; set; }
        public string L1_SubjectName_2 { get; set; }
        public string L2_SubjectName_2 { get; set; }
        public string College_3 { get; set; }
        public string DegreeOfInterest_3 { get; set; }
        public string School_3 { get; set; }
        public string AOI1_3 { get; set; }
        public string AOI2_3 { get; set; }
        public string L1_SubjectName_3 { get; set; }
        public string L2_SubjectName_3 { get; set; }
        public string appname { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> call_date { get; set; }
        public string audio_link { get; set; }
        public string College_4 { get; set; }
        public string DegreeOfInterest_4 { get; set; }
        public string School_4 { get; set; }
        public string AOI1_4 { get; set; }
        public string AOI2_4 { get; set; }
        public string L1_SubjectName_4 { get; set; }
        public string L2_SubjectName_4 { get; set; }
        public string College_5 { get; set; }
        public string DegreeOfInterest_5 { get; set; }
        public string School_5 { get; set; }
        public string AOI1_5 { get; set; }
        public string AOI2_5 { get; set; }
        public string L1_SubjectName_5 { get; set; }
        public string L2_SubjectName_5 { get; set; }
        public string profile_id { get; set; }
        public string Modality_1 { get; set; }
        public string Modality_2 { get; set; }
        public string Modality_3 { get; set; }
        public string Modality_4 { get; set; }
        public string Modality_5 { get; set; }
    }
}
