//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class additional_pay
    {
        public int id { get; set; }
        public Nullable<System.DateTime> week_ending { get; set; }
        public Nullable<double> add_time { get; set; }
        public Nullable<double> add_money { get; set; }
        public string username { get; set; }
        public string who_added { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string notes { get; set; }
    }
}
