//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_setting_back
    {
        public string recording_url { get; set; }
        public string recording_user { get; set; }
        public string record_password { get; set; }
        public string appname { get; set; }
        public int id { get; set; }
        public string recording_dirs { get; set; }
        public string wav_key { get; set; }
        public string url_prefix { get; set; }
        public string manager { get; set; }
        public Nullable<bool> uses_notifications { get; set; }
    }
}
