//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing_rates
    {
        public int id { get; set; }
        public string appname { get; set; }
        public Nullable<int> start_minutes { get; set; }
        public Nullable<int> end_minutes { get; set; }
        public Nullable<double> rate { get; set; }
        public string bill_type { get; set; }
        public Nullable<int> scorecard_only { get; set; }
    }
}
