//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class calibration_form
    {
        public int id { get; set; }
        public Nullable<int> original_form { get; set; }
        public string reviewed_by { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public Nullable<decimal> total_score { get; set; }
        public Nullable<decimal> total_score_with_fails { get; set; }
        public string calibration_comment { get; set; }
        public Nullable<System.DateTime> review_started { get; set; }
        public Nullable<double> cali_form_score { get; set; }
        public Nullable<double> cali_dev { get; set; }
        public Nullable<double> original_score { get; set; }
        public Nullable<bool> selected { get; set; }
        public Nullable<int> isRecal { get; set; }
        public Nullable<double> recal_score { get; set; }
        public Nullable<int> active_cali { get; set; }
        public string formatted_missed_c { get; set; }
        public string formatted_comments_c { get; set; }
        public Nullable<int> num_missed_c { get; set; }
        public Nullable<int> cQAwhisper { get; set; }
        public Nullable<int> cwhisperID { get; set; }
        public Nullable<System.DateTime> cwhisper_forgiven { get; set; }
        public string cwhisper_forgiven_by { get; set; }
        public string missed_list_c { get; set; }
        public Nullable<int> c_pending_id { get; set; }
        public Nullable<bool> use_for_training { get; set; }
        public string calibrator_calibrated { get; set; }
    }
}
