//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSAutoSaleRep
    {
        public int id { get; set; }
        public Nullable<int> xcc_id { get; set; }
        public Nullable<int> sales_id { get; set; }
        public string sales_rep { get; set; }
    }
}
