//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class csCallType
    {
        public int id { get; set; }
        public Nullable<int> cs_id { get; set; }
        public string cs_text { get; set; }
        public Nullable<int> xcc_id { get; set; }
    }
}
