//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dba_indexDefragExclusion
    {
        public int databaseID { get; set; }
        public string databaseName { get; set; }
        public int objectID { get; set; }
        public string objectName { get; set; }
        public int indexID { get; set; }
        public string indexName { get; set; }
        public int exclusionMask { get; set; }
    }
}
