//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_routing
    {
        public Nullable<int> sc_id { get; set; }
        public Nullable<bool> email_notifications { get; set; }
        public Nullable<bool> email_fails { get; set; }
        public string agent_group { get; set; }
        public string campaign { get; set; }
        public string email_list { get; set; }
        public int id { get; set; }
        public string username { get; set; }
        public Nullable<bool> email_wrong { get; set; }
    }
}
