//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedUserProfile
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public string userName { get; set; }
        public int hoursPerWeek { get; set; }
        public int daysPerWeek { get; set; }
        public Nullable<int> prefStartHour { get; set; }
    }
}
