//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class filter_data
    {
        public int id { get; set; }
        public string filter_key { get; set; }
        public string filter_format { get; set; }
        public string filter_data_type { get; set; }
    }
}
