//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_q_scores_options_training
    {
        public int id { get; set; }
        public string option_value { get; set; }
        public Nullable<double> option_pos { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<int> form_id { get; set; }
        public Nullable<int> orig_id { get; set; }
        public Nullable<int> option_id { get; set; }
    }
}
