//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class grand_data
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string email { get; set; }
        public string number1 { get; set; }
        public string DISPOSITION { get; set; }
        public string TIMESTAMP { get; set; }
        public Nullable<System.DateTime> real_time { get; set; }
        public int id { get; set; }
    }
}
