//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class heatbeat_data
    {
        public int id { get; set; }
        public string who { get; set; }
        public Nullable<System.DateTime> hb_date { get; set; }
        public Nullable<int> x_id { get; set; }
    }
}
