//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inactive_users
    {
        public int id { get; set; }
        public string username { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email_address { get; set; }
        public string phone_number { get; set; }
        public string Address_text { get; set; }
        public string mobile_number { get; set; }
        public string skype_name { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<int> speed_increment { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public string default_appname { get; set; }
        public Nullable<bool> calls_start_immediately { get; set; }
        public Nullable<double> speed_limit { get; set; }
        public Nullable<int> desktopwidth { get; set; }
        public string user_group { get; set; }
        public string Gender { get; set; }
        public string user_role { get; set; }
        public Nullable<System.DateTime> lastLoginDate { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<decimal> starting_salary { get; set; }
        public Nullable<bool> can_edit { get; set; }
        public Nullable<System.DateTime> lastActiveDate { get; set; }
        public Nullable<int> guideline_display { get; set; }
        public Nullable<bool> non_edit { get; set; }
        public Nullable<int> call_center { get; set; }
        public string special_filter { get; set; }
        public string default_page { get; set; }
        public Nullable<bool> shift_approved { get; set; }
        public string manager_group { get; set; }
        public Nullable<bool> special { get; set; }
        public string manager { get; set; }
        public Nullable<System.DateTime> original_start_date { get; set; }
        public Nullable<decimal> original_starting_salary { get; set; }
        public Nullable<bool> presubmit { get; set; }
        public string ipaddress { get; set; }
        public string export_type { get; set; }
        public Nullable<int> use_qa_pay { get; set; }
        public Nullable<bool> no_dash { get; set; }
        public string user_appname { get; set; }
        public Nullable<bool> force_review { get; set; }
        public Nullable<bool> bypass { get; set; }
        public Nullable<bool> externalUser { get; set; }
        public Nullable<bool> non_calib { get; set; }
        public string qa_tier { get; set; }
        public Nullable<bool> shift_qa { get; set; }
        public Nullable<int> hour_per_week { get; set; }
        public Nullable<int> shift_id { get; set; }
        public Nullable<bool> excludeCalls { get; set; }
    }
}
