//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class linked_items
    {
        public int id { get; set; }
        public Nullable<int> linked_parent_question { get; set; }
        public Nullable<int> linked_to_question { get; set; }
        public string linked_type { get; set; }
        public Nullable<int> linked_item_id { get; set; }
        public Nullable<bool> initially_visible { get; set; }
    }
}
