//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification_steps
    {
        public int id { get; set; }
        public string appname { get; set; }
        public string role { get; set; }
        public Nullable<bool> admin { get; set; }
        public Nullable<bool> client { get; set; }
        public Nullable<bool> manager { get; set; }
        public Nullable<bool> supervisor { get; set; }
        public Nullable<bool> agent { get; set; }
        public Nullable<bool> QA { get; set; }
        public Nullable<bool> calibrator { get; set; }
        public Nullable<bool> TL { get; set; }
        public Nullable<bool> CM { get; set; }
        public Nullable<bool> scorecard { get; set; }
        public Nullable<int> profile_id { get; set; }
        public Nullable<bool> client_calibrator { get; set; }
        public Nullable<bool> tango_tl { get; set; }
        public Nullable<bool> account_manager { get; set; }
    }
}
