//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_instructions
    {
        public int id { get; set; }
        public Nullable<int> question_id { get; set; }
        public string question_text { get; set; }
        public string answer_type { get; set; }
        public Nullable<int> q_order { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
    }
}
