//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_summary_data
    {
        public Nullable<System.DateTime> call_date { get; set; }
        public int id { get; set; }
        public Nullable<int> q_wrong { get; set; }
        public Nullable<int> q_right { get; set; }
        public string agent_group { get; set; }
        public string agent { get; set; }
    }
}
