//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class sc_training_approvals
    {
        public int id { get; set; }
        public string username { get; set; }
        public Nullable<int> sc_id { get; set; }
        public Nullable<System.DateTime> sc_date { get; set; }
        public string sc_by { get; set; }
        public string train_status { get; set; }
        public Nullable<System.DateTime> retrain_date { get; set; }
    }
}
