//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class school_update_list
    {
        public int id { get; set; }
        public string incoming { get; set; }
        public string outgoing { get; set; }
        public string by_who { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
    }
}
