//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class scorecard_changes
    {
        public int id { get; set; }
        public Nullable<int> scorecard { get; set; }
        public string change { get; set; }
        public string changed_by { get; set; }
        public Nullable<System.DateTime> changed_date { get; set; }
    }
}
