//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int id { get; set; }
        public string section1 { get; set; }
        public Nullable<int> section_order { get; set; }
        public string Descrip { get; set; }
        public string appname { get; set; }
        public Nullable<int> orig_id { get; set; }
        public Nullable<bool> serious { get; set; }
        public Nullable<int> scorecard_id { get; set; }
        public Nullable<double> max_score_loss { get; set; }
    }
}
