//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class session_viewed
    {
        public int ID { get; set; }
        public string agent { get; set; }
        public Nullable<System.DateTime> date_viewed { get; set; }
        public Nullable<int> session_id { get; set; }
        public Nullable<System.DateTime> date_completed { get; set; }
        public string page_viewed { get; set; }
    }
}
