//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApp
    {
        public int id { get; set; }
        public string username { get; set; }
        public string appname { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public string who_added { get; set; }
        public Nullable<int> user_priority { get; set; }
        public Nullable<System.DateTime> trained_date { get; set; }
        public Nullable<int> max_per_day { get; set; }
        public Nullable<int> user_scorecard { get; set; }
        public string scorecard_role { get; set; }
        public Nullable<int> speed_increment { get; set; }
        public Nullable<int> userid { get; set; }
    }
}
