//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vb_keywords
    {
        public int id { get; set; }
        public Nullable<int> form_id { get; set; }
        public string category { get; set; }
        public string keyword { get; set; }
        public Nullable<int> relevance { get; set; }
    }
}
