//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTrain
    {
        public string short_name { get; set; }
        public int id { get; set; }
        public string session_id { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public Nullable<int> review_ID { get; set; }
        public string Comments { get; set; }
        public string autofail { get; set; }
        public string reviewer { get; set; }
        public string appname { get; set; }
        public string dispute { get; set; }
        public Nullable<System.DateTime> dispute_date { get; set; }
        public string dispute_by { get; set; }
        public string agent_comment { get; set; }
        public Nullable<System.DateTime> agent_reviewed { get; set; }
        public string Supervisor_comment { get; set; }
        public Nullable<System.DateTime> Supervisor_reviewed { get; set; }
        public Nullable<double> total_score { get; set; }
        public Nullable<double> total_score_with_fails { get; set; }
        public Nullable<int> old_review_id { get; set; }
        public Nullable<bool> has_cardinal { get; set; }
        public string fs_audio { get; set; }
        public Nullable<System.DateTime> week_ending_date { get; set; }
        public Nullable<int> num_missed { get; set; }
        public string missed_list { get; set; }
        public Nullable<System.DateTime> call_made_date { get; set; }
        public Nullable<double> agent_deviation { get; set; }
        public Nullable<double> calib_deviation { get; set; }
        public Nullable<int> calib_id { get; set; }
        public Nullable<double> trainee_score { get; set; }
        public Nullable<double> original_score { get; set; }
        public int train_id { get; set; }
        public int sc_id { get; set; }
        public Nullable<double> call_length { get; set; }
        public Nullable<int> scorecard { get; set; }
        public int F_ID { get; set; }
        public string AGENT { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string phone { get; set; }
        public string EducationLevel { get; set; }
        public string HighSchoolGradYear { get; set; }
        public string DegreeStartTimeframe { get; set; }
        public string CAMPAIGN { get; set; }
        public string address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string ANI { get; set; }
        public string DNIS { get; set; }
        public Nullable<System.DateTime> call_date { get; set; }
        public string audio_link { get; set; }
        public string audio_user { get; set; }
        public string audio_password { get; set; }
        public Nullable<System.DateTime> CALL_TIME { get; set; }
        public Nullable<decimal> cali_form_score { get; set; }
        public Nullable<bool> wasEdited { get; set; }
        public Nullable<int> X_ID { get; set; }
        public string website { get; set; }
        public string rev_first { get; set; }
        public string rev_last { get; set; }
        public string CALL_TYPE { get; set; }
        public string DISPOSITION { get; set; }
        public string compliance_sheet { get; set; }
        public Nullable<decimal> calib_score { get; set; }
        public Nullable<decimal> edited_score { get; set; }
        public string profile_id { get; set; }
        public string transcript { get; set; }
        public string formatted_transcript { get; set; }
        public Nullable<System.DateTime> transcript_analyzed { get; set; }
        public string website_display { get; set; }
        public string Scorecard_name { get; set; }
        public string leadid { get; set; }
        public Nullable<bool> is_practice { get; set; }
    }
}
