//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class xl_mortgage_import
    {
        public int id { get; set; }
        public string lender { get; set; }
        public Nullable<int> scorecard { get; set; }
        public Nullable<int> import_percent { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
    }
}
