//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class agenda_topic_responses
    {
        public int id { get; set; }
        public string who_created { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string topic_answer { get; set; }
        public Nullable<int> topic_id { get; set; }
    }
}
