//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_access
    {
        public int id { get; set; }
        public string ip { get; set; }
        public string value { get; set; }
        public string value_type { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string posted_appname { get; set; }
    }
}
