//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class calibration_scores
    {
        public int id { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<int> form_id { get; set; }
        public Nullable<int> question_result { get; set; }
        public string score_comment { get; set; }
        public Nullable<double> q_pos { get; set; }
        public Nullable<double> percent_pos { get; set; }
        public string view_link { get; set; }
        public string click_text { get; set; }
        public Nullable<bool> wasMissed { get; set; }
    }
}
