//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_data
    {
        public int id { get; set; }
        public string chat_id { get; set; }
        public string visitor_name { get; set; }
        public string agent_name { get; set; }
        public string duration { get; set; }
        public string agent_group { get; set; }
        public string chat_started { get; set; }
        public string tags { get; set; }
        public string existing_customer { get; set; }
    }
}
