//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class csTempXCC
    {
        public int id { get; set; }
        public string session_id { get; set; }
        public string campaign { get; set; }
        public Nullable<System.DateTime> call_date { get; set; }
        public Nullable<int> scorecard { get; set; }
        public string audio_link { get; set; }
        public string appname { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
