//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbl_users
    {
        public string dbl_user_name { get; set; }
        public string dbl_type { get; set; }
        public int id { get; set; }
        public string real_name { get; set; }
    }
}
