//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class eduff_websites
    {
        public string Partners { get; set; }
        public string School { get; set; }
        public string URL { get; set; }
        public int id { get; set; }
        public string notes { get; set; }
        public string comp_sheet { get; set; }
    }
}
