//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class extra_user_hours
    {
        public int id { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> week_ending { get; set; }
        public Nullable<double> worked_hours { get; set; }
        public Nullable<int> isapproved { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
    }
}
