//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_q_scores_save
    {
        public int id { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<int> form_id { get; set; }
        public Nullable<int> question_result { get; set; }
        public string q_position { get; set; }
        public Nullable<int> question_answered { get; set; }
        public Nullable<int> answer_comment { get; set; }
        public string other_answer_text { get; set; }
        public string click_text { get; set; }
        public Nullable<double> percent_pos { get; set; }
        public Nullable<double> avg_pos { get; set; }
        public Nullable<int> original_question_answered { get; set; }
        public string view_link { get; set; }
        public Nullable<bool> calib_match { get; set; }
    }
}
