//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPI_sites
    {
        public int id { get; set; }
        public string URL { get; set; }
        public string Partner { get; set; }
        public string school { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
