//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword_Changes
    {
        public int ID { get; set; }
        public int Scorecard { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Update_Type { get; set; }
        public string Keyword_From { get; set; }
        public string Keyword_To { get; set; }
        public Nullable<int> Min_Count_From { get; set; }
        public Nullable<int> Min_Count_To { get; set; }
        public string Problem_From { get; set; }
        public string Problem_To { get; set; }
        public string Utterance_Type_From { get; set; }
        public string Utterance_Type_To { get; set; }
        public string Accepted_Variant_From { get; set; }
        public string Accepted_Variant_To { get; set; }
        public Nullable<bool> Mandatory_Review_From { get; set; }
        public Nullable<bool> Mandatory_Review_To { get; set; }
    }
}
