//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class messaging
    {
        public int id { get; set; }
        public string from_login { get; set; }
        public string to_login { get; set; }
        public string message_text { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public Nullable<System.DateTime> dateclosed { get; set; }
        public Nullable<int> forward_id { get; set; }
        public string object_table { get; set; }
        public Nullable<int> object_table_id { get; set; }
        public string subject { get; set; }
    }
}
