//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_data
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postal { get; set; }
        public string yearGraduated { get; set; }
        public string levelOfEducation { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string Military_Y_N { get; set; }
        public string Campaign { get; set; }
        public string Program { get; set; }
        public string Location { get; set; }
        public string Campus_prf { get; set; }
        public string Mth__to_start { get; set; }
        public bool Has_comp_ { get; set; }
        public string Gender { get; set; }
        public string Best_time { get; set; }
        public string Status { get; set; }
        public string Agent_name { get; set; }
    }
}
