//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class qs_agent_08092018
    {
        public string agent { get; set; }
        public string agent_name { get; set; }
        public string agent_group { get; set; }
        public int id { get; set; }
    }
}
