//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_rules
    {
        public int id { get; set; }
        public string rule_type { get; set; }
        public string rule_source { get; set; }
        public string rule_operator { get; set; }
        public string rule_value { get; set; }
        public Nullable<int> qc_id { get; set; }
    }
}
