//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.question_answers = new HashSet<question_answers>();
        }
    
        public int id { get; set; }
        public Nullable<int> section { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> q_order { get; set; }
        public string question1 { get; set; }
        public string q_type { get; set; }
        public string q_short_name { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> heading { get; set; }
        public Nullable<int> Order { get; set; }
        public string QuestionText { get; set; }
        public Nullable<double> q_percent { get; set; }
        public string appname { get; set; }
        public Nullable<bool> auto_yes { get; set; }
        public Nullable<bool> auto_no { get; set; }
        public string agent_display { get; set; }
        public Nullable<int> default_answer { get; set; }
        public Nullable<int> orig_id { get; set; }
        public Nullable<double> total_points { get; set; }
        public string template { get; set; }
        public string template_items { get; set; }
        public string linked_question { get; set; }
        public Nullable<bool> email_wrong { get; set; }
        public string campaign_specific { get; set; }
        public Nullable<int> scorecard_id { get; set; }
        public Nullable<double> QA_points { get; set; }
        public Nullable<bool> compliance { get; set; }
        public Nullable<System.DateTime> date_q_added { get; set; }
        public Nullable<bool> non_billable { get; set; }
        public Nullable<bool> comments_allowed { get; set; }
        public Nullable<int> linked_answer { get; set; }
        public Nullable<int> linked_comment { get; set; }
        public Nullable<int> client_visible { get; set; }
        public Nullable<bool> client_guideline_visible { get; set; }
        public Nullable<int> Sectionless_Order { get; set; }
        public Nullable<bool> linked_visible { get; set; }
        public Nullable<bool> client_dashboard_visible { get; set; }
        public Nullable<bool> pinned { get; set; }
        public Nullable<bool> pre_production { get; set; }
        public Nullable<bool> single_comment { get; set; }
        public Nullable<bool> points_paused { get; set; }
        public Nullable<System.DateTime> points_paused_date { get; set; }
        public Nullable<bool> full_width { get; set; }
        public Nullable<bool> wide_q { get; set; }
        public Nullable<bool> require_custom_comment { get; set; }
        public string sentence { get; set; }
        public string ddl_type { get; set; }
        public string ddlQuery { get; set; }
        public string options_verb { get; set; }
        public Nullable<bool> left_column_question { get; set; }
        public Nullable<int> univeral_postition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question_answers> question_answers { get; set; }
    }
}
