//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class sc_inputs
    {
        public int id { get; set; }
        public Nullable<int> scorecard { get; set; }
        public string value { get; set; }
        public string notes { get; set; }
        public string value_type { get; set; }
        public Nullable<int> value_order { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> required_value { get; set; }
        public Nullable<bool> dash_visible { get; set; }
    }
}
