//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_X_Data
    {
        public int id { get; set; }
        public string School { get; set; }
        public string AOI1 { get; set; }
        public string AOI2 { get; set; }
        public string L1_SubjectName { get; set; }
        public string L2_SubjectName { get; set; }
        public string Modality { get; set; }
        public Nullable<int> xcc_id { get; set; }
        public string College { get; set; }
        public string DegreeOfInterest { get; set; }
        public string origin { get; set; }
        public string tcpa { get; set; }
    }
}
