//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftItem
    {
        public int shiftID { get; set; }
        public string dayName { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public string HOUR00 { get; set; }
        public string HOUR01 { get; set; }
        public string HOUR02 { get; set; }
        public string HOUR03 { get; set; }
        public string HOUR04 { get; set; }
        public string HOUR05 { get; set; }
        public string HOUR06 { get; set; }
        public string HOUR07 { get; set; }
        public string HOUR08 { get; set; }
        public string HOUR09 { get; set; }
        public string HOUR10 { get; set; }
        public string HOUR11 { get; set; }
        public string HOUR12 { get; set; }
        public string HOUR13 { get; set; }
        public string HOUR14 { get; set; }
        public string HOUR15 { get; set; }
        public string HOUR16 { get; set; }
        public string HOUR17 { get; set; }
        public string HOUR18 { get; set; }
        public string HOUR19 { get; set; }
        public string HOUR20 { get; set; }
        public string HOUR21 { get; set; }
        public string HOUR22 { get; set; }
        public string HOUR23 { get; set; }
    }
}
