//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class spot_perf
    {
        public string short_name { get; set; }
        public string team_lead { get; set; }
        public string reviewer { get; set; }
        public Nullable<int> total_calls { get; set; }
        public Nullable<int> total_100s { get; set; }
        public Nullable<decimal> avg_cali { get; set; }
        public int id { get; set; }
        public Nullable<int> spot_count_100 { get; set; }
        public Nullable<int> spot_percent_100 { get; set; }
        public Nullable<int> spot_percent_cali { get; set; }
        public Nullable<int> spot_count_cali { get; set; }
        public string assigned_to { get; set; }
        public Nullable<decimal> percent_100s { get; set; }
    }
}
