//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class spot_auto
    {
        public int id { get; set; }
        public Nullable<int> QID { get; set; }
        public string assigned_to { get; set; }
        public Nullable<int> wrong_percent { get; set; }
        public Nullable<int> wrong_count { get; set; }
        public Nullable<int> calib_percent { get; set; }
        public Nullable<int> calib_count { get; set; }
        public string spot_check_note { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
