//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class update_mgmt
    {
        public int id { get; set; }
        public Nullable<int> scorecard { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string who_created { get; set; }
        public string status { get; set; }
        public string function_list { get; set; }
        public Nullable<System.DateTime> go_live { get; set; }
        public string update_name { get; set; }
    }
}
