//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class utterance_template
    {
        public int id { get; set; }
        public string Utterance { get; set; }
        public string Problem { get; set; }
        public string utterance_type { get; set; }
        public string accepted_variant { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
