//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public int id { get; set; }
        public string vendor_name { get; set; }
        public string vendor_prefix { get; set; }
        public string contact { get; set; }
        public string phone { get; set; }
        public Nullable<double> @base { get; set; }
    }
}
