//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCaliForm
    {
        public int id { get; set; }
        public Nullable<double> call_length { get; set; }
        public string appname { get; set; }
        public Nullable<System.DateTime> week_ending_date { get; set; }
    }
}
