//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCF
    {
        public int F_ID { get; set; }
        public int id { get; set; }
        public Nullable<double> recal_score { get; set; }
        public Nullable<int> isRecal { get; set; }
        public Nullable<double> original_score { get; set; }
        public Nullable<System.DateTime> review_started { get; set; }
        public Nullable<decimal> total_score { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public string reviewed_by { get; set; }
        public Nullable<int> original_form { get; set; }
        public string appname { get; set; }
        public string reviewer { get; set; }
        public Nullable<double> call_length { get; set; }
        public Nullable<System.DateTime> week_ending_date { get; set; }
        public Nullable<bool> onAWS { get; set; }
        public Nullable<int> scorecard { get; set; }
        public string website { get; set; }
        public Nullable<double> cali_form_score { get; set; }
        public Nullable<int> active_cali { get; set; }
        public string formatted_comments_c { get; set; }
        public string formatted_missed_c { get; set; }
        public Nullable<int> num_missed_c { get; set; }
        public string pass_fail { get; set; }
        public string AGENT { get; set; }
        public Nullable<System.DateTime> call_date { get; set; }
        public Nullable<decimal> calib_score { get; set; }
        public Nullable<bool> wasEdited { get; set; }
        public string AGENT_GROUP { get; set; }
        public string phone { get; set; }
        public string CAMPAIGN { get; set; }
        public string Scorecard_name { get; set; }
        public string SESSION_ID { get; set; }
        public string team_lead { get; set; }
        public Nullable<int> review_ID { get; set; }
        public string audio_link { get; set; }
        public Nullable<int> cQAwhisper { get; set; }
        public Nullable<int> cwhisperID { get; set; }
        public string missed_list_c { get; set; }
        public Nullable<double> display_score { get; set; }
        public string calibration_comment { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string EducationLevel { get; set; }
        public string HighSchoolGradYear { get; set; }
        public string DegreeStartTimeframe { get; set; }
        public string CALL_TYPE { get; set; }
        public string DISPOSITION { get; set; }
        public string compliance_sheet { get; set; }
        public string profile_id { get; set; }
        public string address { get; set; }
        public string ANI { get; set; }
        public string DNIS { get; set; }
        public string transcript { get; set; }
        public string formatted_transcript { get; set; }
        public Nullable<int> bad_call { get; set; }
        public Nullable<System.DateTime> CALL_TIME { get; set; }
        public Nullable<decimal> edited_score { get; set; }
        public Nullable<System.DateTime> transcript_analyzed { get; set; }
        public string sc_review_type_calib { get; set; }
        public string leadid { get; set; }
        public Nullable<bool> use_for_training { get; set; }
        public Nullable<bool> client_visible { get; set; }
        public string calibrator_calibrated { get; set; }
        public Nullable<int> num_missed_a { get; set; }
        public Nullable<int> num_missed_q { get; set; }
        public Nullable<int> num_missed_cal { get; set; }
        public Nullable<System.DateTime> xcc_review_date { get; set; }
    }
}
