//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFN
    {
        public int FN_ID { get; set; }
        public string role { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_closed { get; set; }
        public string close_reason { get; set; }
        public string closed_by { get; set; }
        public Nullable<double> form_position { get; set; }
        public string opened_by { get; set; }
        public Nullable<int> sup_override { get; set; }
        public int F_ID { get; set; }
        public Nullable<int> review_ID { get; set; }
        public string Comments { get; set; }
        public string autofail { get; set; }
        public string reviewer { get; set; }
        public string appname { get; set; }
        public Nullable<decimal> total_score { get; set; }
        public Nullable<decimal> total_score_with_fails { get; set; }
        public Nullable<double> call_length { get; set; }
        public Nullable<bool> has_cardinal { get; set; }
        public string fs_audio { get; set; }
        public Nullable<System.DateTime> week_ending_date { get; set; }
        public Nullable<int> num_missed { get; set; }
        public string missed_list { get; set; }
        public Nullable<System.DateTime> call_made_date { get; set; }
        public string AGENT { get; set; }
        public string ANI { get; set; }
        public string DNIS { get; set; }
        public string TIMESTAMP { get; set; }
        public string TALK_TIME { get; set; }
        public Nullable<System.DateTime> CALL_TIME { get; set; }
        public string CALL_TYPE { get; set; }
        public string leadid { get; set; }
        public string AGENT_GROUP { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<double> Datacapturekey { get; set; }
        public Nullable<double> Datacapture { get; set; }
        public string Status { get; set; }
        public string Program { get; set; }
        public int X_ID { get; set; }
        public string Datacapture_Status { get; set; }
        public string num_of_schools { get; set; }
        public Nullable<int> MAX_REVIEWS { get; set; }
        public Nullable<System.DateTime> review_started { get; set; }
        public string Number_of_Schools { get; set; }
        public string EducationLevel { get; set; }
        public string HighSchoolGradYear { get; set; }
        public string DegreeStartTimeframe { get; set; }
        public string Expr3 { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> call_date { get; set; }
        public string audio_link { get; set; }
        public string profile_id { get; set; }
        public string audio_user { get; set; }
        public string audio_password { get; set; }
        public string LIST_NAME { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public string CAMPAIGN { get; set; }
        public string DISPOSITION { get; set; }
        public Nullable<int> bad_call { get; set; }
        public Nullable<bool> to_upload { get; set; }
        public string SESSION_ID { get; set; }
        public Nullable<double> agent_deviation { get; set; }
        public string pass_fail { get; set; }
        public Nullable<int> scorecard { get; set; }
        public Nullable<System.DateTime> escalated { get; set; }
        public Nullable<System.DateTime> escalated_closed { get; set; }
        public string formatted_comments { get; set; }
        public Nullable<bool> wasEdited { get; set; }
        public string website { get; set; }
        public Nullable<bool> first_10 { get; set; }
        public string Scorecard_name { get; set; }
        public string team_lead { get; set; }
        public Nullable<bool> mgr_sees { get; set; }
        public string notification_status { get; set; }
        public Nullable<double> fn_display_score { get; set; }
        public Nullable<bool> client_visible { get; set; }
        public Nullable<System.DateTime> xcc_review_date { get; set; }
    }
}
