//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class weekly_CPS
    {
        public int id { get; set; }
        public string reviewer { get; set; }
        public Nullable<double> cps { get; set; }
        public Nullable<System.DateTime> week_ending { get; set; }
        public Nullable<double> cps_call { get; set; }
        public Nullable<double> cps_review { get; set; }
    }
}
