//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class xcc_report_new_pending
    {
        public string SESSION_ID { get; set; }
        public string AGENT { get; set; }
        public string DISPOSITION { get; set; }
        public string CAMPAIGN { get; set; }
        public string ANI { get; set; }
        public string DNIS { get; set; }
        public string TIMESTAMP { get; set; }
        public string TALK_TIME { get; set; }
        public string CALL_TIME { get; set; }
        public string HANDLE_TIME { get; set; }
        public string CALL_TYPE { get; set; }
        public string LIST_NAME { get; set; }
        public string leadid { get; set; }
        public string AGENT_GROUP { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<double> Datacapturekey { get; set; }
        public Nullable<double> Datacapture { get; set; }
        public string Status { get; set; }
        public string Program { get; set; }
        public int ID { get; set; }
        public string Datacapture_Status { get; set; }
        public string num_of_schools { get; set; }
        public Nullable<int> MAX_REVIEWS { get; set; }
        public Nullable<System.DateTime> review_started { get; set; }
        public string Number_of_Schools { get; set; }
        public string EducationLevel { get; set; }
        public string HighSchoolGradYear { get; set; }
        public string DegreeStartTimeframe { get; set; }
        public string appname { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> call_date { get; set; }
        public string audio_link { get; set; }
        public string profile_id { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string AreaOfInterest { get; set; }
        public string ProgramsOfInterestType { get; set; }
        public string Citizenship { get; set; }
        public string Gender { get; set; }
        public string Military { get; set; }
        public string DegreeOfInterest { get; set; }
        public string secondphone { get; set; }
        public string agent_name { get; set; }
        public Nullable<int> scorecard { get; set; }
        public string xcc_report_new_pending1 { get; set; }
        public string website { get; set; }
        public Nullable<double> call_duration { get; set; }
        public string hold_time { get; set; }
        public Nullable<int> sort_order { get; set; }
    }
}
