//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class xrn_io
    {
        public int id { get; set; }
        public string phone { get; set; }
        public string session_id { get; set; }
        public string direction { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
        public Nullable<System.DateTime> original_date_added { get; set; }
        public Nullable<int> original_id { get; set; }
        public string appname { get; set; }
    }
}
